# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: Zafirr
email: zafirr@sekai.team
name: Zafirr 
description: >- # this means to ignore newlines until "baseurl:"
  Random things about cybersecurity, compsci, and the environment 
keywords: research, writeups, blog
baseurl: '' # the subpath of your site, e.g. /`blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'blog.zafirr.dev' # the domain name for your site, e.g. example.com
language: en

comments: false # enable comments
disqus: # disqus account

mathjax: false # Math support
diagram: false # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: "/:path"

sass:
  sass_dir: _sass
  style: compact # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
