# Site settings
title: "Zafirr's Blog"
email: zafir.r.taufik@gmail.com
description: "TODO"
baseurl: ""
url: "https://zafirr.dev/"
title_description: "TODO"
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  zafirr31
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/zafir-rasyidi-taufik/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>, thanks a lot!"
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
