# Site settings
title: "Zafirr's Blog"
email: zafir.r.taufik@gmail.com
description: "Zafirr's blog about cybersecurity and other stuff "
baseurl: ""
url: "https://zafirr.dev/"
title_description: "Hi, this is my blog for stuff I find interesting and want to share. It can be anything, but will mostly consist of cybersecurity related stuff like CTFs and my research. If you wish to contact me, please message me on discord or email me. Thanks!"
title_image: "https://www.gravatar.com/avatar/6cdfa49a75ee00d338ea88c1ba1c24eb?s=500&d=mm"
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  zafirr31
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/zafir-rasyidi-taufik/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:
discord_userid: 506294850291892226

# Footer
footer_left: "Theme by <a href=\"https://carte-noire.jacobtomlinson.co.uk/\">Jacob Tomlinson</a>, thanks a lot!"
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
